Repository snowhite-hyu/backend, pull requests merged in 2025-06, with the labels that each got.

#28 [SH-30] 라운드 종료 구현
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/service/UserService.java
  src/main/java/com/snowhite/server/web/controller/RoomController.java
  src/main/java/com/snowhite/server/web/controller/UserController.java
  src/main/java/com/snowhite/server/web/dto/request/EmailDto.java
  src/main/java/com/snowhite/server/web/dto/request/LoginRequestDto.java
  src/main/java/com/snowhite/server/web/dto/request/RegisterDto.java
  src/main/java/com/snowhite/server/web/dto/response/EmailCheckResponseDto.java
  src/main/java/com/snowhite/server/web/dto/response/GetRoomResponse.java
  src/main/java/com/snowhite/server/web/dto/response/LoginResponseDto.java
  src/main/java/com/snowhite/server/web/dto/response/RegisterResponseDto.java
  src/main/java/com/snowhite/server/web/dto/response/StartGameResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/GameResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/PublicPlayerResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/SecretPlayerResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundGameResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundPlayersResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundResponse.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/main/resources/application.properties
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
Labels: :sparkles: Enhancement, :recycle: Refactor

#30 [SH-91] 카드 가져오기 기능 구현
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/test/java/com/snowhite/server/service/GameServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
  src/test/java/com/snowhite/server/service/UseActionCardServiceTest.java
Labels: :sparkles: Enhancement

#33 [FIX] 오류 수정
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
Labels: :bug: BugFix

#32 [SH-78] 방 객체에 Name 속성 추가
  src/main/java/com/snowhite/server/domain/session/Room.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :recycle: Refactor

#34 [FEAT] 세션 prefix 분리
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
Labels: :bug: BugFix, :sparkles: Enhancement

#35 [FIX] Game 역직렬화 오류 수정
  src/main/java/com/snowhite/server/config/JacksonConfig.java
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/domain/enums/PlayerState.java
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :bug: BugFix

#39 [SH-89] 행동카드 응답 DTO 리팩토링
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/domain/entity/Card.java
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/init/CardInitializer.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/websocket/dto/request/ActionCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/request/BrokenCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/request/MapCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/request/RepairCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/request/RockfallCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/response/ActionCardUsedResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/PublicPlayerResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/ResponseType.java
  src/main/java/com/snowhite/server/websocket/dto/response/SecretPlayerResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/BrokenResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/GameChangedResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/MapResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/RepairResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/RockfallResult.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/resources/application.properties
  src/test/java/com/snowhite/server/service/GameWebSocketHandlerTest.java
  src/test/java/com/snowhite/server/service/UseActionCardServiceTest.java
Labels: :recycle: Refactor

#42 [Fix] prefix 분리에 따른 행동카드 handler 수정
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :bug: BugFix

#44 [FIX] 카드 정보 수정
  src/main/java/com/snowhite/server/init/CardInitializer.java
Labels: :bug: BugFix

#45 [SH-89] 행동카드 응답에 turn 추가 및 리팩토링
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/websocket/dto/UseBrokenCardResultDTO.java
  src/main/java/com/snowhite/server/websocket/dto/UseMapCardResultDTO.java
  src/main/java/com/snowhite/server/websocket/dto/UseRepairCardDTO.java
  src/main/java/com/snowhite/server/websocket/dto/UseRockfallCardResultDTO.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/BrokenResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/GameChangedResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/MapResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/RepairResult.java
  src/main/java/com/snowhite/server/websocket/dto/response/action/RockfallResult.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :sparkles: Enhancement, :recycle: Refactor

#36 [SH-80] handler / service 책임 분리
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/dto/RoomServiceResult.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :recycle: Refactor

#47 [REVERT] 잘못된 병합 revert
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/dto/RoomServiceResult.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :bug: BugFix

#48 [Hotfix] 빌드 에러 수정
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/GameServiceTest.java
  src/test/java/com/snowhite/server/service/RoomServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
  src/test/java/com/snowhite/server/service/UseActionCardServiceTest.java
  src/test/java/com/snowhite/server/web/controller/RoomControllerTest.java
Labels: :bug: BugFix

#46 [SH-173] 라운드 시작 refactoring
  .gitignore
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/dto/NextRoundResultDTO.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundGameResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundPlayersResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/nextround/NextRoundResponse.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :sparkles: Enhancement, :recycle: Refactor

#49 [hotfix] 빌드 에러 수정
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/dto/RoomServiceResultDTO.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/GameServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
  src/test/java/com/snowhite/server/service/UseActionCardServiceTest.java
Labels: :bug: BugFix

#38 [SH-172] 채팅 기능 구현
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :sparkles: Enhancement

#51 [FEAT] 굴 카드 배치 로직 추가
  src/main/java/com/snowhite/server/service/GameService.java
Labels: :sparkles: Enhancement

#53 [SH-177] 망가진 도구 보유 플레이어가 굴 카드 사용되는 이슈 해결
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/service/GameService.java
Labels: :bug: BugFix

#58 [SH-199] 방장 퇴장 시, 방 삭제
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :sparkles: Enhancement

#59 [SH-182] 행동 카드 에러 메시지 형태 수정
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :bug: BugFix

#60 [hotfix] field 크기 변경에 맞춰 초기화 수정
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix

#61 [FIX] 게임 시작 시 방 제거 삭제
  src/main/java/com/snowhite/server/service/RoomService.java
Labels: :bug: BugFix

#63 [FIX] 지도 사용 조건 수정
  src/main/java/com/snowhite/server/service/GameService.java
Labels: :bug: BugFix

#65 [hotfix] 카드가 없는 곳에 낙석 사용 못하도록 수정
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix

#66 [FIX] 라운드 종료 오류 해결
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix

#67 [FIX] 연결 갱신 수정
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix

#68 [FIX] 굴 카드 배치 시 연결 갱신 안되는 문제 해결
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix

#69 [FIX] 라운드 종료 후 멈추는 이슈 해결
  src/main/java/com/snowhite/server/domain/session/Game.java
Labels: :bug: BugFix
