Repository snowhite-hyu/backend, pull requests merged in 2025-05, with the labels that each got.

#6 [SH-82] 회원가입 구현
  build.gradle
  src/main/java/com/snowhite/server/config/SecurityConfig.java
  src/main/java/com/snowhite/server/domain/Card.java
  src/main/java/com/snowhite/server/domain/CardType.java
  src/main/java/com/snowhite/server/domain/File.java
  src/main/java/com/snowhite/server/domain/User.java
  src/main/java/com/snowhite/server/domain/UserRepository.java
  src/main/java/com/snowhite/server/domain/common/BaseEntity.java
  src/main/java/com/snowhite/server/dto/EmailDto.java
  src/main/java/com/snowhite/server/dto/RegisterDto.java
  src/main/java/com/snowhite/server/payload/exception/ExceptionAdvice.java
  src/main/java/com/snowhite/server/service/UserService.java
  src/main/java/com/snowhite/server/web/controller/UserController.java
Labels: :sparkles: Enhancement

#8 [SH-77] 방 리스트 조회 기능 구현
  src/main/java/com/snowhite/server/domain/Room.java
  src/main/java/com/snowhite/server/domain/User.java
  src/main/java/com/snowhite/server/service/LobbyService.java
  src/main/java/com/snowhite/server/web/controller/LobbyController.java
  src/main/java/com/snowhite/server/web/controller/LobbyRouter.java
  src/main/java/com/snowhite/server/web/service/LobbyHandler.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/web/service/LobbyHandlerTest.java
Labels: :sparkles: Enhancement

#9 [SH-77] 중복 파일 삭제
  src/main/java/com/snowhite/server/web/controller/LobbyController.java
  src/main/java/com/snowhite/server/web/controller/LobbyRouter.java
  src/main/java/com/snowhite/server/web/service/LobbyHandler.java
Labels: :recycle: Refactor

#12 [SH-77] 방 리스트 조회 기능 버그 수정
  src/main/java/com/snowhite/server/config/JwtWebFilter.java
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/config/SecurityConfig.java
  src/main/java/com/snowhite/server/domain/Room.java
  src/main/java/com/snowhite/server/domain/UserRepository.java
  src/main/java/com/snowhite/server/service/LobbyService.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/web/service/LobbyHandlerTest.java
Labels: :bug: BugFix

#13 fix : 방 리스트 조회 기능 에러 수정
  src/main/java/com/snowhite/server/config/JacksonConfig.java
  src/main/java/com/snowhite/server/payload/ApiResponse.java
  src/main/java/com/snowhite/server/service/LobbyService.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
Labels: :bug: BugFix

#15 [SH-55] 게임 시작 기능 구현
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/config/WebSocketConfig.java
  src/main/java/com/snowhite/server/domain/entity/Card.java
  src/main/java/com/snowhite/server/domain/entity/File.java
  src/main/java/com/snowhite/server/domain/entity/User.java
  src/main/java/com/snowhite/server/domain/enums/CardType.java
  src/main/java/com/snowhite/server/domain/enums/PlayerState.java
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/domain/session/Room.java
  src/main/java/com/snowhite/server/repository/UserRepository.java
  src/main/java/com/snowhite/server/security/filter/JwtWebFilter.java
  src/main/java/com/snowhite/server/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/snowhite/server/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/snowhite/server/security/jwt/JwtProvider.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/service/LobbyService.java
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/service/UserService.java
  src/main/java/com/snowhite/server/web/controller/LobbyController.java
  src/main/java/com/snowhite/server/web/controller/RoomController.java
  src/main/java/com/snowhite/server/web/controller/UserController.java
  src/main/java/com/snowhite/server/web/dto/EmailDto.java
  src/main/java/com/snowhite/server/web/dto/web/request/LoginRequestDto.java
  src/main/java/com/snowhite/server/web/dto/web/request/RegisterDto.java
  src/main/java/com/snowhite/server/web/dto/web/response/GetRoomResponse.java
  src/main/java/com/snowhite/server/web/dto/web/response/LoginResponseDto.java
  src/main/java/com/snowhite/server/websocket/dto/request/GameJoinRequest.java
  src/main/java/com/snowhite/server/websocket/dto/response/SimpleMessageResponse.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :sparkles: Enhancement

#16 [SH-12] Security Config 병합 에러 수정
  build.gradle
  src/main/java/com/snowhite/server/config/SecurityConfig.java
  src/main/java/com/snowhite/server/security/filter/JwtWebFilter.java
  src/main/java/com/snowhite/server/service/UserService.java
  src/main/java/com/snowhite/server/web/controller/UserController.java
Labels: :bug: BugFix

#18 [SH-79] 방 참가 기능 리팩토링 및 테스트 코드 오류 수정
  src/main/java/com/snowhite/server/config/SecurityConfig.java
  src/main/java/com/snowhite/server/config/WebSocketConfig.java
  src/main/java/com/snowhite/server/domain/session/Room.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :bug: BugFix, :recycle: Refactor

#19 [SH-56] 라운드 시작 기능 구현
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/config/SecurityConfig.java
  src/main/java/com/snowhite/server/config/WebSocketConfig.java
  src/main/java/com/snowhite/server/domain/entity/Card.java
  src/main/java/com/snowhite/server/domain/entity/File.java
  src/main/java/com/snowhite/server/domain/enums/CardType.java
  src/main/java/com/snowhite/server/domain/enums/GameState.java
  src/main/java/com/snowhite/server/domain/enums/PlayerRole.java
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/init/CardInitializer.java
  src/main/java/com/snowhite/server/payload/WsMessage.java
  src/main/java/com/snowhite/server/repository/CardRepository.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/service/RoomService.java
  src/main/java/com/snowhite/server/web/controller/RoomController.java
  src/main/java/com/snowhite/server/web/controller/UserController.java
  src/main/java/com/snowhite/server/web/dto/web/response/StartGameResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/PlayerJoinedResponse.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :sparkles: Enhancement

#22 [SH-163] 게임 모든 정보 조회
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
Labels: :sparkles: Enhancement

#23 [SH-80] 방 퇴장 기능 추가 및 여러 수정사항
  src/main/java/com/snowhite/server/domain/entity/User.java
  src/main/java/com/snowhite/server/websocket/handler/RoomWebSocketHandler.java
  src/test/java/com/snowhite/server/service/LobbyServiceTest.java
  src/test/java/com/snowhite/server/service/RoomWebSocketHandlerTest.java
Labels: :bug: BugFix, :sparkles: Enhancement, :recycle: Refactor

#26 Hotfix
  src/main/resources/application.properties
Labels: :bug: BugFix

#27 [SH-89] 행동카드 사용 구현
  src/main/java/com/snowhite/server/config/RedisConfig.java
  src/main/java/com/snowhite/server/domain/entity/ActionCard.java
  src/main/java/com/snowhite/server/domain/entity/Card.java
  src/main/java/com/snowhite/server/domain/entity/DestinationCard.java
  src/main/java/com/snowhite/server/domain/entity/PathCard.java
  src/main/java/com/snowhite/server/domain/entity/StartCard.java
  src/main/java/com/snowhite/server/domain/entity/User.java
  src/main/java/com/snowhite/server/domain/enums/ActionCardType.java
  src/main/java/com/snowhite/server/domain/enums/CardType.java
  src/main/java/com/snowhite/server/domain/enums/PlayerState.java
  src/main/java/com/snowhite/server/domain/factory/CardFactory.java
  src/main/java/com/snowhite/server/domain/session/Game.java
  src/main/java/com/snowhite/server/domain/session/Player.java
  src/main/java/com/snowhite/server/init/CardInitializer.java
  src/main/java/com/snowhite/server/payload/code/status/WsErrorStatus.java
  src/main/java/com/snowhite/server/payload/exception/BusinessException.java
  src/main/java/com/snowhite/server/payload/exception/WebSocketException.java
  src/main/java/com/snowhite/server/repository/CardRepository.java
  src/main/java/com/snowhite/server/service/GameService.java
  src/main/java/com/snowhite/server/websocket/dto/request/ActionCardUseRequest.java
  src/main/java/com/snowhite/server/websocket/dto/response/ActionCardUsedResponse.java
  src/main/java/com/snowhite/server/websocket/dto/response/ResponseType.java
  src/main/java/com/snowhite/server/websocket/handler/GameWebSocketHandler.java
  src/main/resources/application.properties
  src/test/java/com/snowhite/server/service/GameWebSocketHandlerTest.java
  src/test/java/com/snowhite/server/service/UseActionCardServiceTest.java
Labels: :sparkles: Enhancement, :recycle: Refactor
